feat: add autocomplete support
flybywiresim/discord-bot-utils pull request #52
Opened 2024-05-12 14:35 UTC by ExampleWasTaken

## Description
This PR adds support for the autocomplete feature of slash commands.

The implementation closely follows the already existing infrastructure by adding a third (and optional) argument for an autocomplete-callback function to the `slashCommand()` function.

## Test Results
This PR has no effect on existing code. It only lays the groundwork for future commands that may require autocompletion.

## Additional Information
This PR is required for #51.

## Discord Username
examplewastaken

2024-05-12 18:26 UTC, benw202 reviewed
Please add `src/lib/autocomplete.ts` to the index.ts file in the lib dir.

You will then need to change your import in slashCommand.ts

2024-05-12 18:50 UTC, ExampleWasTaken commented
Yep good point. Will do.

2024-05-12 20:14 UTC, benw202 requested changes

2024-05-12 20:14 UTC, benw202 commented on src/lib/autocomplete.ts
> +import { LogMethods } from './events';
```suggestion
import { LogMethods } from './index';
```

2024-05-12 20:14 UTC, benw202 commented on src/lib/slashCommand.ts
>  import { LogMethods } from './index';
```suggestion
import { LogMethods, AutocompleteCallback } from './index';
```

2024-05-12 20:14 UTC, benw202 commented on src/lib/slashCommand.ts
> +import { AutocompleteCallback } from './index';
```suggestion
```

2024-05-14 19:28 UTC, benw202 commented on .github/CONTRIBUTING.md
> +        }
```suggestion
        },
```

2024-05-14 19:28 UTC, benw202 commented on .github/CONTRIBUTING.md
> +}
```suggestion
};
```

2024-05-14 19:44 UTC, benw202 approved these changes

2024-05-22 19:28 UTC, pdellaert approved these changes

2024-05-23 09:49 UTC, merged